### ISSUE TITLE
ModuleNotFoundError: No module named 'edlib'

### ISSUE THREAD

**Issue by snayfach** [rrwick/Badread#15]
I installed the program using: `conda install -c bioconda badread -y`

But got the error:

> Traceback (most recent call last):
>   File "/global/homes/s/snayfach/.conda/envs/flye/bin/badread", line 10, in <module>
>     sys.exit(main())
>   File "/global/homes/s/snayfach/.conda/envs/flye/lib/python3.8/site-packages/badread/__main__.py", line 33, in main
>     from .simulate import simulate
>   File "/global/homes/s/snayfach/.conda/envs/flye/lib/python3.8/site-packages/badread/simulate.py", line 17, in <module>
>     import edlib
> ModuleNotFoundError: No module named 'edlib'

The issue appears to be discussed [here](https://github.com/Martinsos/edlib/issues/102)

The solution was to run this: `conda install python-edlib -y`

Would be helpful to future users if you could add this to the bioconda recipe or mention this in the docs.

Thanks,
Stephen

**Comment by sarahjeeeze** [comment]
Thank you so much

**Comment by mbhall88** [comment]
This has been resolved now (https://github.com/bioconda/bioconda-recipes/pull/41633). The latest build version (0.4.0) on bioconda fixes this
